### ISSUE TITLE
double free or corruption on connect

### ISSUE THREAD

**Issue by cristinabolanospeno** [oscaracena/pygattlib#19]
I'm connecting periodically to my device, and everything works fine, until at some point my program stops with one of the following:
- double free or corruption (fasttop)
- free(): double free detected in tcache2

While debugging it, this is what I discovered:
1. `getsockopt` in /src/bluez/btio/btio.c:281 returns non-zero result and `gerr` is set at line 287.
   ```shell
   Thread 2 "python3" hit Breakpoint 2, connect_cb (io=0xb4805008, cond=<optimized out>, user_data=0xb3e03708)
       at src/bluez/btio/btio.c:287
   287	src/bluez/btio/btio.c: No existe el fichero o el directorio.
   (gdb) p err
   $1 = -107
   (gdb) next
   289	in src/bluez/btio/btio.c
   (gdb) p gerr
   $2 = (GError *) 0xb3e02730
   ```
2. Then it goes to /src/gattlib.cpp:314 and calls `g_free_error` on `gerr`.
   ```shell
   (gdb) c
   Continuing.
   PyGattLib ERROR: connect error: Transport endpoint is not connected (107)

   Thread 2 "python3" hit Breakpoint 1, connect_cb (channel=<optimized out>, err=0xb3e02730, userp=0xb6508b88)
      at src/gattlib.cpp:314
   314	src/gattlib.cpp: No existe el fichero o el directorio.
   (gdb) p err
   $4 = (GError *) 0xb3e02730
   (gdb) p *err
   $5 = {domain = 1, code = 107, message = 0xb4800f80 "connect error: Transport endpoint is not connected (107)"}
   (gdb) next
   315	in src/gattlib.cpp
   (gdb) p err
   $6 = (GError *) 0xb3e02730
   (gdb) p *err
   $7 = {domain = 3017921120, code = 0, message = 0xb4800f80 ""}
   ```
3. Back at /src/bluez/btio/btio.c:291 calls `g_clear_error` on `gerr`, which is not NULL, and aborts the program.
   ```shell
   (gdb) c
   Continuing.
   double free or corruption (fasttop)
   ```

Is there a way I can try-catch this error? Or maybe, call `g_clear_error` instead of `g_free_error` in /src/gattlib.cpp:314? It would set `*gerr` to NULL, as it says [GLib Documentation](https://developer.gnome.org/glib/stable/glib-Error-Reporting.html#g-clear-error).

**Comment by MOAMIndustries** [comment]
I am hitting this same issue. Although mine is consistently when trying to write_by_handle to a characteristic that enables notifications. Did you find a solution for this problem?

**Comment by cristinabolanospeno** [comment]
Not at the time. For now I restart the program each time it crashes, which isn't a fancy solution... That's why a try-catch would be fine, like 'connection went wrong, so not doing action'.

**Comment by jsgh** [comment]
It is just wrong of gattlib.cpp to be freeing the error object here, if the caller is going to do so, so we should remove that line.

And we can't change it to g_clear_error either since we only have access to our own copy of the pointer, not to the caller's, because it's passed as a pointer not a pointer-to-pointer like g_clear_error takes, so the caller would still see a non-NULL value and crash.

**Comment by MOAMIndustries** [comment]
Tested today. 
#22 fixes the crash. 
However the error `'PyGattLib ERROR: connect error: Function not implemented (38)'
Is still printed  to the terminal as it attempts writing a characteristic.

I think it should throw an exception. Unfortunately its a bit outside of my abilities yet to know how to implement this.

```2021-03-26 10:23:57,085] INFO     __main__     enabling notifications
[2021-03-26 10:23:57,086] DEBUG    __main__     enabling notifications on: 66:77:71:2D:55:V5
PyGattLib ERROR: connect error: Function not implemented (38)

PyGattLib ERROR: connect error: Function not implemented (38)

[2021-03-26 10:24:07,348] INFO     __main__     spin
[2021-03-26 10:24:07,849] INFO     __main__     spin```

**Comment by jsgh** [comment]
It can't throw an exception because we're in a callback on a worker thread, and there is no python on the stack to throw the exception *to*.

It does however call on_connect_failed(err) on your overridden GATTRequester object, that is how you can detect the error in your own code. (Now that we have that callback we can probably remove that output. Or move it to the default callback implementation as is done for the other callbacks.)

(Hmm. You probably shouldn't be trying to enable notifications, or do any kind of transfer, until the on_connect() callback has happened. Not that much will happen: the implementation should just queue your request packet until the connection is in a suitable state to send it out.)
